version: '3.8'

x-networks:
  app-network:


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_data:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    ports:
      - "5173:5173"
      - "8000:8000"

  db:
    image: postgres:13
    ports:
      - "31543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=your_new_password
    networks:
      - app-network

volumes:
  postgres_data:
  app_data:


networks:
  app-network:
    driver: bridge
